# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-16 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='answered_by',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='asked_by',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
