# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-15 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='created_by',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
